server:
  port: 8763
spring:
  profiles: 8763
  application:
    name: eureka-service

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
---
server:
  port: 8762
spring:
  profiles: 8762
  application:
    name: eureka-service

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/